services:

  producer-bin-01:
      build:
        context: .
        dockerfile: Dockerfile
      privileged: true
      devices:
        - "/dev/gpiomem0:/dev/gpiomem"
        - "/dev/gpiochip0:/dev/gpiochip0"
      cpus: 0.5
      restart: unless-stopped
      command: >
        python3 -u producer.py
          --device-id pir-01
          --pin 17
          --sample-interval 0.5
          --cooldown 2
          --min-high 0.3
          --duration 999999
          --broker BROKER_IP=10.144.118.81
          --port 1883
          --event-topic smartbin/bin-01/pir-01/events
          --status-topic smartbin/bin-01/pir-01/status
          --qos 1
          --verbose
          --ha-config-topic homeassistant/binary_sensor/pir-01/config
          --ha-event-topic homeassistant/binary_sensor/pir-01/events
    
# networks:
#   mqtt-net:
#     external: true